In [2]:
import numpy as np

In [39]:
x = np.array(([3,4], [1,2], [5,6], [7,8], [9,10], [11,12]))

In [32]:
x

array([[ 3,  4],
       [ 1,  2],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [25]:
k = 3
np.random.shuffle(x)
splitted = np.split(x, k)

In [26]:
print(splitted)

[array([[ 7,  8],
       [ 9, 10]]), array([[ 3,  4],
       [11, 12]]), array([[1, 2],
       [5, 6]])]


In [27]:
splitted.pop(1)

array([[ 3,  4],
       [11, 12]])

In [28]:
arr = np.vstack(splitted)

In [29]:
arr

array([[ 7,  8],
       [ 9, 10],
       [ 1,  2],
       [ 5,  6]])

In [44]:

cv = 3
data = np.array(([3,4], [1,2], [5,6], [7,8], [9,10], [11,12]))
for k in range(cv):
    splitted = np.split(data, cv)
    test = splitted.pop(k)
    train = np.vstack(splitted)
    print(test, train)


[[3 4]
 [1 2]] [[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[5 6]
 [7 8]] [[ 3  4]
 [ 1  2]
 [ 9 10]
 [11 12]]
[[ 9 10]
 [11 12]] [[3 4]
 [1 2]
 [5 6]
 [7 8]]


In [20]:
a = np.vstack((np.ones((1,2)) * 4, np.ones((1,2)) * 2, np.ones((1,2)) * 3, np.ones((1,2)) * 5))

In [21]:
a

array([[4., 4.],
       [2., 2.],
       [3., 3.],
       [5., 5.]])

In [22]:
b = np.ones((1,2))
b

array([[1., 1.]])

In [23]:
def distance(x, y):
        return np.sqrt(np.sum((x-y)**2, axis=1))

In [40]:
d = enumerate(distance(a,b))
for i, x in d:
    print (i, x)

0 4.242640687119285
1 1.4142135623730951
2 2.8284271247461903
3 5.656854249492381


In [34]:
np.sort(d)

array([1.41421356, 2.82842712, 4.24264069, 5.65685425])

In [32]:
idx = np.argsort(d)[:3]

In [33]:
a[idx]

array([[2., 2.],
       [3., 3.],
       [4., 4.]])